// Generated by CoffeeScript 1.7.1
(function() {
  var executeTime;

  executeTime = 1;

  setInterval(function() {
    var iframe, src;
    iframe = $('#ip_zdaye_com');
    src = iframe.attr('src');
    if ('&' === src.substr(-1)) {
      src = src.slice(0, -1);
    } else {
      src += '&';
    }
    iframe.attr('src', src);
    return chrome.browserAction.setBadgeText({
      text: "" + (++executeTime)
    });
  }, 60 * 1000 * 15);

}).call(this);
